name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build & Test (Xcode ${{ matrix.xcode_version }})
    runs-on: macos-11
    strategy:
      matrix:
        xcode_version: ['12.5.1', '13.1']
    env:
      DEVELOPER_DIR: '/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Check Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run Tests
      run: swift test -v

  run_swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Lint Files
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
